def math():
    print("Math Commands:")
    print("math add int1 int2: add int1 and int2")
    print("math areac radius : returns the area of a circle from the given radius")
    print("math areacf radius : returns a non-rounded area of a circle from the given radius")
    print("math circumc d : returns the circumference of a circle from the given diameter")
    print("math circumc r : returns the circumference of a circle from the given radius")
    print("math div int1 int2: divide int1 and int2")
    print("math dtor int : converts diameter to radius")
    print("math mult int1 int2: multiply int1 and int2")
    print("math pow int1 int2: returns int1 to the power of int2")
    print("math rtod int : converts radius to diameter")
    print("math sqr int : returns the square of int")
    print("math sqrt int : returns the square root of int")
    print("math sub int1 int2: subtract int1 and int2")
def fib():
    print("Fibonacci Commands:")
    print("fib gen int : to generate a fibonacci sequence")
def caesar():
    print("Moving three letters backwards ex: a = d, b = e, c = f, etc.")
    print("Caesar Cipher Commands:")
    print("caesar dec string : decode string to a normal string")
    print("caesar enc string : encode string to a caesar cipher")
def atbash():
    print("Reversing letters ex: a = z, b = y, c = x, etc.")
    print("Atbash Cipher Commands:")
    print("atbash dec string : decode string to a normal string")
    print("atbash enc string : encode string to a caesar cipher")
def a1z26():
    print("Changing letters to numbers ex: a = 1, b = 2, c = 3, etc.")
    print("A1Z26 Commands:")
    print("a1z dec string : decode numbers to a string")
    print("a1z enc string : encode string to an A126 cipher")
def general():
    print("help atbash : return commands of the Atbash Cipher commands")
    print("help a1z : return commands of the A1Z26 Cipher commands")
    print("help caesar : return commands of the Caesar Cipher commands")
    print("help fib : return commands of the Fibonacci Sequence commands")
    print("help math : return commands of Math commands")
    print("help : returns this menu")
    print("q : quits the script")